import pandas as pd

# Define the translation dictionary for column names
translation_dict = {
    "NAME OF DATA ELEMENT": "数据名",
    'Unit ID for institution': "机构单位ID",
    "8-digit OPE ID for institution": "机构8位OPE ID",
    "6-digit OPE ID for institution": "机构6位OPE ID",
    "Institution name": "机构名称",
    "City": "城市",
    "State postcode": "州邮政编码",
    "ZIP code": "邮政编码",
    "Accreditor for institution": "机构认证机构",
    "URL for institution's homepage": "机构主页网址",
    "URL for institution's net price calculator": "机构净价计算器网址",
    "Predominant degree awarded (recoded 0s and 4s)": "主要授予学位(重新编码为0和4)",
    "Schools that are on Heightened Cash Monitoring 2 by the Department of Education": "受教育部加强现金监控2的学校",
    "Flag for main campus": "主校区标志",
    "Number of branch campuses": "分校数量",
    "Predominant undergraduate degree awarded": "主要本科学位授予",
    "Highest degree awarded": "最高学位授予",
    "Control of institution (IPEDS)": "机构控制类型(IPEDS)",
    "FIPS code for state": "州的FIPS编码",
    "Region (IPEDS)": "地区(IPEDS)",
    "Locale of institution": "机构所在地区",
    "Degree of urbanization of institution": "机构城市化程度",
    "Latitude": "纬度",
    "Longitude": "经度",
    "Carnegie Classification -- basic": "卡内基分类 - 基础",
    "Carnegie Classification -- undergraduate profile": "卡内基分类 - 本科生档案",
    "Carnegie Classification -- size and setting": "卡内基分类 - 大小和环境",
    "Flag for Historically Black College and University": "历史性黑人学院和大学标志",
    "Flag for predominantly black institution": "主要黑人机构标志",
    "Flag for Alaska Native Native Hawaiian serving institution": "为阿拉斯加原住民和夏威夷原住民服务的机构标志",
    "Flag for tribal college and university": "部落学院和大学标志",
    "Flag for Asian American Native American Pacific Islander-serving institution": "为亚裔美国人、土著美国人和太平洋岛民服务的机构标志",
    "Flag for Hispanic-serving institution": "为西班牙裔服务的机构标志",
    "Flag for Native American non-tribal institution": "非部落土著美国人机构标志",
    "Flag for men-only college": "男性专属学院标志",
    "Flag for women-only college": "女性专属学院标志",
    "Religious affiliation of the institution": "机构的宗教隶属关系",
    "Admission rate": "录取率",
    "Admission rate for all campuses rolled up to the 6-digit OPE ID": "所有校区的录取率(整合到6位OPE ID)",
    "25th percentile of SAT scores at the institution (critical reading)": "机构SAT分数25th百分位数(阅读部分）",
    "75th percentile of SAT scores at the institution (critical reading)": "机构SAT分数75th百分位数(阅读部分）",
    "25th percentile of SAT scores at the institution (math)": "机构SAT分数25th百分位数(数学部分）",
    "75th percentile of SAT scores at the institution (math)": "机构SAT分数75th百分位数(数学部分）",
    "25th percentile of SAT scores at the institution (writing)": "机构SAT分数25th百分位数(写作部分）",
    "75th percentile of SAT scores at the institution (writing)": "机构SAT分数75th百分位数(写作部分）",
    "Midpoint of SAT scores at the institution (critical reading)": "机构SAT分数中点(阅读部分）",
    "Midpoint of SAT scores at the institution (math)": "机构SAT分数中点(数学部分）",
    "Midpoint of SAT scores at the institution (writing)": "机构SAT分数中点(写作部分）",
    "25th percentile of the ACT cumulative score": "ACT综合分数25th百分位数",
    "75th percentile of the ACT cumulative score": "ACT综合分数75th百分位数",
    "25th percentile of the ACT English score": "ACT英语分数25th百分位数",
    "75th percentile of the ACT English score": "ACT英语分数75th百分位数",
    "25th percentile of the ACT math score": "ACT数学分数25th百分位数",
    "75th percentile of the ACT math score": "ACT数学分数75th百分位数",
    "25th percentile of the ACT writing score": "ACT写作分数25th百分位数",
    "75th percentile of the ACT writing score": "ACT写作分数75th百分位数",
    "Midpoint of the ACT cumulative score": "ACT综合分数中点",
    "Midpoint of the ACT English score": "ACT英语分数中点",
    "Midpoint of the ACT math score": "ACT数学分数中点",
    "Midpoint of the ACT writing score": "ACT写作分数中点",
    "Average SAT equivalent score of students admitted": "录取学生平均SAT等效分数",
    "Average SAT equivalent score of students admitted for all campuses rolled up to the 6-digit OPE ID": "所有校区录取学生平均SAT等效分数(整合到6位OPE ID)",
    "Percentage of degrees awarded in Agriculture, Agriculture Operations, And Related Sciences.": "农业、农业操作及相关科学学位授予比例",
    "Percentage of degrees awarded in Natural Resources And Conservation.": "自然资源和保护学位授予比例",
    "Percentage of degrees awarded in Architecture And Related Services.": "建筑及相关服务学位授予比例",
    "Percentage of degrees awarded in Area, Ethnic, Cultural, Gender, And Group Studies.": "区域、种族、文化、性别和群体研究学位授予比例",
    "Percentage of degrees awarded in Communication, Journalism, And Related Programs.": "传播、新闻及相关项目学位授予比例",
    "Percentage of degrees awarded in Communications Technologies/Technicians And Support Services.": "通讯技术/技术人员及支持服务学位授予比例",
    "Percentage of degrees awarded in Computer And Information Sciences And Support Services.": "计算机及信息科学与支持服务学位授予比例",
    "Percentage of degrees awarded in Personal And Culinary Services.": "个人及烹饪服务学位授予比例",
    "Percentage of degrees awarded in Education.": "教育学位授予比例",
    "Percentage of degrees awarded in Engineering.": "工程学位授予比例",
    "Percentage of degrees awarded in Engineering Technologies And Engineering-Related Fields.": "工程技术及相关领域学位授予比例",
    "Percentage of degrees awarded in Foreign Languages, Literatures, And Linguistics.": "外语、文学及语言学学位授予比例",
    "Percentage of degrees awarded in Family And Consumer Sciences/Human Sciences.": "家庭与消费者科学学位授予比例",
    "Percentage of degrees awarded in Legal Professions And Studies.": "法律职业与研究学位授予比例",
    "Percentage of degrees awarded in English Language And Literature/Letters.": "英语语言与文学/文学学位授予比例",
    "Percentage of degrees awarded in Liberal Arts And Sciences, General Studies And Humanities.": "文理学院、通识教育与人文学科学位授予比例",
    "Percentage of degrees awarded in Library Science.": "图书馆学科学位授予比例",
    "Percentage of degrees awarded in Biological And Biomedical Sciences.": "生物与生物医学科学学位授予比例",
    "Percentage of degrees awarded in Mathematics And Statistics.": "数学与统计学学位授予比例",
    "Percentage of degrees awarded in Military Technologies And Applied Sciences.": "军事技术及应用科学学位授予比例",
    "Percentage of degrees awarded in Multi/Interdisciplinary Studies.": "多/跨学科研究学位授予比例",
    "Percentage of degrees awarded in Parks, Recreation, Leisure, And Fitness Studies.": "公园、娱乐、休闲及健身研究学位授予比例",
    "Percentage of degrees awarded in Philosophy And Religious Studies.": "哲学与宗教研究学位授予比例",
    "Percentage of degrees awarded in Theology And Religious Vocations.": "神学与宗教职业学位授予比例",
    "Percentage of degrees awarded in Physical Sciences.": "物理科学学位授予比例",
    "Percentage of degrees awarded in Science Technologies/Technicians.": "科学技术/技术人员学位授予比例",
    "Percentage of degrees awarded in Psychology.": "心理学学位授予比例",
    "Percentage of degrees awarded in Homeland Security, Law Enforcement, Firefighting And Related Protective Services.": "国土安全、执法、消防及相关防护服务学位授予比例",
    "Percentage of degrees awarded in Public Administration And Social Service Professions.": "公共行政与社会服务职业学位授予比例",
    "Percentage of degrees awarded in Social Sciences.": "社会科学学位授予比例",
    "Percentage of degrees awarded in Construction Trades.": "建筑贸易学位授予比例",
    "Percentage of degrees awarded in Mechanic And Repair Technologies/Technicians.": "机械与修理技术/技术人员学位授予比例",
    "Percentage of degrees awarded in Precision Production.": "精密生产学位授予比例",
    "Percentage of degrees awarded in Transportation And Materials Moving.": "运输与材料运输学位授予比例",
    "Percentage of degrees awarded in Visual And Performing Arts.": "视觉与表演艺术学位授予比例",
    "Percentage of degrees awarded in Health Professions And Related Programs.": "健康专业及相关项目学位授予比例",
    "Percentage of degrees awarded in Business, Management, Marketing, And Related Support Services.": "商业、管理、市场营销及相关支持服务学位授予比例",
    "Percentage of degrees awarded in History.": "历史学位授予比例",
    "Certificate of less than one academic year in Agriculture, Agriculture Operations, And Related Sciences.": "农业、农业操作及相关科学学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Agriculture, Agriculture Operations, And Related Sciences.": "农业、农业操作及相关科学学术年度至少一年但少于两年的证书",
    "Associate degree in Agriculture, Agriculture Operations, And Related Sciences.": "农业、农业操作及相关科学副学士学位",
    "Award of at least two but less than four academic years in Agriculture, Agriculture Operations, And Related Sciences.": "农业、农业操作及相关科学学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Agriculture, Agriculture Operations, And Related Sciences.": "农业、农业操作及相关科学学士学位",
    "Certificate of less than one academic year in Natural Resources And Conservation.": "自然资源及保护学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Natural Resources And Conservation.": "自然资源及保护学术年度至少一年但少于两年的证书",
    "Associate degree in Natural Resources And Conservation.": "自然资源及保护副学士学位",
    "Award of at least two but less than four academic years in Natural Resources And Conservation.": "自然资源及保护学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Natural Resources And Conservation.": "自然资源及保护学士学位",
    "Certificate of less than one academic year in Architecture And Related Services.": "建筑及相关服务学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Architecture And Related Services.": "建筑及相关服务学术年度至少一年但少于两年的证书",
    "Associate degree in Architecture And Related Services.": "建筑及相关服务副学士学位",
    "Award of at least two but less than four academic years in Architecture And Related Services.": "建筑及相关服务学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Architecture And Related Services.": "建筑及相关服务学士学位",
    "Certificate of less than one academic year in Area, Ethnic, Cultural, Gender, And Group Studies.": "区域、种族、文化、性别及群体研究学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Area, Ethnic, Cultural, Gender, And Group Studies.": "区域、种族、文化、性别及群体研究学术年度至少一年但少于两年的证书",
    "Associate degree in Area, Ethnic, Cultural, Gender, And Group Studies.": "区域、种族、文化、性别及群体研究副学士学位",
    "Award of at least two but less than four academic years in Area, Ethnic, Cultural, Gender, And Group Studies.": "区域、种族、文化、性别及群体研究学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Area, Ethnic, Cultural, Gender, And Group Studies.": "区域、种族、文化、性别及群体研究学士学位",
    "Certificate of less than one academic year in Communication, Journalism, And Related Programs.": "传播、新闻及相关项目学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Communication, Journalism, And Related Programs.": "传播、新闻及相关项目学术年度至少一年但少于两年的证书",
    "Associate degree in Communication, Journalism, And Related Programs.": "传播、新闻及相关项目副学士学位",
    "Award of at least two but less than four academic years in Communication, Journalism, And Related Programs.": "传播、新闻及相关项目学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Communication, Journalism, And Related Programs.": "传播、新闻及相关项目学士学位",
    "Certificate of less than one academic year in Communications Technologies/Technicians And Support Services.": "通讯技术/技术人员及支持服务学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Communications Technologies/Technicians And Support Services.": "通讯技术/技术人员及支持服务学术年度至少一年但少于两年的证书",
    "Associate degree in Communications Technologies/Technicians And Support Services.": "通讯技术/技术人员及支持服务副学士学位",
    "Award of at least two but less than four academic years in Communications Technologies/Technicians And Support Services.": "通讯技术/技术人员及支持服务学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Communications Technologies/Technicians And Support Services.": "通讯技术/技术人员及支持服务学士学位",
    "Certificate of less than one academic year in Computer And Information Sciences And Support Services.": "计算机及信息科学与支持服务学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Computer And Information Sciences And Support Services.": "计算机及信息科学与支持服务学术年度至少一年但少于两年的证书",
    "Associate degree in Computer And Information Sciences And Support Services.": "计算机及信息科学与支持服务副学士学位",
    "Award of at least two but less than four academic years in Computer And Information Sciences And Support Services.": "计算机及信息科学与支持服务学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Computer And Information Sciences And Support Services.": "计算机及信息科学与支持服务学士学位",
    "Certificate of less than one academic year in Personal And Culinary Services.": "个人及烹饪服务学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Personal And Culinary Services.": "个人及烹饪服务学术年度至少一年但少于两年的证书",
    "Associate degree in Personal And Culinary Services.": "个人及烹饪服务副学士学位",
    "Award of at least two but less than four academic years in Personal And Culinary Services.": "个人及烹饪服务学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Personal And Culinary Services.": "个人及烹饪服务学士学位",
    "Certificate of less than one academic year in Education.": "教育学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Education.": "教育学术年度至少一年但少于两年的证书",
    "Associate degree in Education.": "教育副学士学位",
    "Award of at least two but less than four academic years in Education.": "教育学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Education.": "教育学士学位",
    "Certificate of less than one academic year in Engineering.": "工程学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Engineering.": "工程学术年度至少一年但少于两年的证书",
    "Associate degree in Engineering.": "工程副学士学位",
    "Award of at least two but less than four academic years in Engineering.": "工程学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Engineering.": "工程学士学位",
    "Certificate of less than one academic year in Engineering Technologies And Engineering-Related Fields.": "工程技术及相关领域学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Engineering Technologies And Engineering-Related Fields.": "工程技术及相关领域学术年度至少一年但少于两年的证书",
    "Associate degree in Engineering Technologies And Engineering-Related Fields.": "工程技术及相关领域副学士学位",
    "Award of at least two but less than four academic years in Engineering Technologies And Engineering-Related Fields.": "工程技术及相关领域学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Engineering Technologies And Engineering-Related Fields.": "工程技术及相关领域学士学位",
    "Certificate of less than one academic year in Foreign Languages, Literatures, And Linguistics.": "外语、文学及语言学学术年度少于一年的证书",
    "Certificate of at least one but less than two academic years in Foreign Languages, Literatures, And Linguistics.": "外语、文学及语言学学术年度至少一年但少于两年的证书",
    "Associate degree in Foreign Languages, Literatures, And Linguistics.": "外语、文学及语言学副学士学位",
    "Award of at least two but less than four academic years in Foreign Languages, Literatures, And Linguistics.": "外语、文学及语言学学术年度至少两年但少于四年的奖项",
    "Bachelor's degree in Foreign Languages, Literatures, And Linguistics.": "外语、文学及语言学学士学位",
    "Certificate of less than one academic year in Family And Consumer Sciences/Human Sciences.": "家庭与消费者科学/人文科学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Family And Consumer Sciences/Human Sciences.": "家庭与消费者科学/人文科学学年至少一年但不足两年证书。",
    "Associate degree in Family And Consumer Sciences/Human Sciences.": "家庭与消费者科学/人文科学副学士学位。",
    "Award of at least two but less than four academic years in Family And Consumer Sciences/Human Sciences.": "家庭与消费者科学/人文科学学年至少两年但不足四年奖项。",
    "Bachelor's degree in Family And Consumer Sciences/Human Sciences.": "家庭与消费者科学/人文科学学士学位。",
    "Certificate of less than one academic year in Legal Professions And Studies.": "法律职业与研究学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Legal Professions And Studies.": "法律职业与研究学年至少一年但不足两年证书。",
    "Associate degree in Legal Professions And Studies.": "法律职业与研究副学士学位。",
    "Award of at least two but less than four academic years in Legal Professions And Studies.": "法律职业与研究学年至少两年但不足四年奖项。",
    "Bachelor's degree in Legal Professions And Studies.": "法律职业与研究学士学位。",
    "Certificate of less than one academic year in English Language And Literature/Letters.": "英语语言与文学/文学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in English Language And Literature/Letters.": "英语语言与文学/文学学年至少一年但不足两年证书。",
    "Associate degree in English Language And Literature/Letters.": "英语语言与文学/文学副学士学位。",
    "Award of at least two but less than four academic years in English Language And Literature/Letters.": "英语语言与文学/文学学年至少两年但不足四年奖项。",
    "Bachelor's degree in English Language And Literature/Letters.": "英语语言与文学/文学学士学位。",
    "Certificate of less than one academic year in Liberal Arts And Sciences, General Studies And Humanities.": "文理学院、通识教育与人文学科学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Liberal Arts And Sciences, General Studies And Humanities.": "文理学院、通识教育与人文学科学年至少一年但不足两年证书。",
    "Associate degree in Liberal Arts And Sciences, General Studies And Humanities.": "文理学院、通识教育与人文学科副学士学位。",
    "Award of at least two but less than four academic years in Liberal Arts And Sciences, General Studies And Humanities.": "文理学院、通识教育与人文学科学年至少两年但不足四年奖项。",
    "Bachelor's degree in Liberal Arts And Sciences, General Studies And Humanities.": "文理学院、通识教育与人文学科学士学位。",
    "Certificate of less than one academic year in Library Science.": "图书馆学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Library Science.": "图书馆学学年至少一年但不足两年证书。",
    "Associate degree in Library Science.": "图书馆学副学士学位。",
    "Award of at least two but less than four academic years in Library Science.": "图书馆学学年至少两年但不足四年奖项。",
    "Bachelor's degree in Library Science.": "图书馆学学士学位。",
    "Certificate of less than one academic year in Biological And Biomedical Sciences.": "生物与生物医学科学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Biological And Biomedical Sciences.": "生物与生物医学科学学年至少一年但不足两年证书。",
    "Associate degree in Biological And Biomedical Sciences.": "生物与生物医学科学副学士学位。",
    "Award of at least two but less than four academic years in Biological And Biomedical Sciences.": "生物与生物医学科学学年至少两年但不足四年奖项。",
    "Bachelor's degree in Biological And Biomedical Sciences.": "生物与生物医学科学学士学位。",
    "Certificate of less than one academic year in Mathematics And Statistics.": "数学与统计学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Mathematics And Statistics.": "数学与统计学学年至少一年但不足两年证书。",
    "Associate degree in Mathematics And Statistics.": "数学与统计学副学士学位。",
    "Award of at least two but less than four academic years in Mathematics And Statistics.": "数学与统计学学年至少两年但不足四年奖项。",
    "Bachelor's degree in Mathematics And Statistics.": "数学与统计学学士学位。",
    "Certificate of less than one academic year in Military Technologies And Applied Sciences.": "军事技术与应用科学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Military Technologies And Applied Sciences.": "军事技术与应用科学学年至少一年但不足两年证书。",
    "Associate degree in Military Technologies And Applied Sciences.": "军事技术与应用科学副学士学位。",
    "Award of at least two but less than four academic years in Military Technologies And Applied Sciences.": "军事技术与应用科学学年至少两年但不足四年奖项。",
    "Bachelor's degree in Military Technologies And Applied Sciences.": "军事技术与应用科学学士学位。",
    "Certificate of less than one academic year in Multi/Interdisciplinary Studies.": "多/跨学科研究学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Multi/Interdisciplinary Studies.": "多/跨学科研究学年至少一年但不足两年证书。",
    "Associate degree in Multi/Interdisciplinary Studies.": "多/跨学科研究副学士学位。",
    "Award of at least two but less than four academic years in Multi/Interdisciplinary Studies.": "多/跨学科研究学年至少两年但不足四年奖项。",
    "Bachelor's degree in Multi/Interdisciplinary Studies.": "多/跨学科研究学士学位。",
    "Certificate of less than one academic year in Parks, Recreation, Leisure, And Fitness Studies.": "公园、娱乐、休闲与健身研究学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Parks, Recreation, Leisure, And Fitness Studies.": "公园、娱乐、休闲与健身研究学年至少一年但不足两年证书。",
    "Associate degree in Parks, Recreation, Leisure, And Fitness Studies.": "公园、娱乐、休闲与健身研究副学士学位。",
    "Award of at least two but less than four academic years in Parks, Recreation, Leisure, And Fitness Studies.": "公园、娱乐、休闲与健身研究学年至少两年但不足四年奖项。",
    "Bachelor's degree in Parks, Recreation, Leisure, And Fitness Studies.": "公园、娱乐、休闲与健身研究学士学位。",
    "Certificate of less than one academic year in Philosophy And Religious Studies.": "哲学与宗教研究学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Philosophy And Religious Studies.": "哲学与宗教研究学年至少一年但不足两年证书。",
    "Associate degree in Philosophy And Religious Studies.": "哲学与宗教研究副学士学位。",
    "Award of at least two but less than four academic years in Philosophy And Religious Studies.": "哲学与宗教研究学年至少两年但不足四年奖项。",
    "Bachelor's degree in Philosophy And Religious Studies.": "哲学与宗教研究学士学位。",
    "Certificate of less than one academic year in Theology And Religious Vocations.": "神学与宗教职业学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Theology And Religious Vocations.": "神学与宗教职业学年至少一年但不足两年证书。",
    "Associate degree in Theology And Religious Vocations.": "神学与宗教职业副学士学位。",
    "Award of at least two but less than four academic years in Theology And Religious Vocations.": "神学与宗教职业学年至少两年但不足四年奖项。",
    "Bachelor's degree in Theology And Religious Vocations.": "神学与宗教职业学士学位。",
    "Certificate of less than one academic year in Physical Sciences.": "物理科学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Physical Sciences.": "物理科学学年至少一年但不足两年证书。",
    "Associate degree in Physical Sciences.": "物理科学副学士学位。",
    "Award of at least two but less than four academic years in Physical Sciences.": "物理科学学年至少两年但不足四年奖项。",
    "Bachelor's degree in Physical Sciences.": "物理科学学士学位。",
    "Certificate of less than one academic year in Science Technologies/Technicians.": "科学技术/技术人员学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Science Technologies/Technicians.": "科学技术/技术人员学年至少一年但不足两年证书。",
    "Associate degree in Science Technologies/Technicians.": "科学技术/技术人员副学士学位。",
    "Award of at least two but less than four academic years in Science Technologies/Technicians.": "科学技术/技术人员学年至少两年但不足四年奖项。",
    "Bachelor's degree in Science Technologies/Technicians.": "科学技术/技术人员学士学位。",
    "Certificate of less than one academic year in Psychology.": "心理学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Psychology.": "心理学学年至少一年但不足两年证书。",
    "Associate degree in Psychology.": "心理学副学士学位。",
    "Award of at least two but less than four academic years in Psychology.": "心理学学年至少两年但不足四年奖项。",
    "Bachelor's degree in Psychology.": "心理学学士学位。",
    "Certificate of less than one academic year in Homeland Security, Law Enforcement, Firefighting And Related Protective Services.": "国土安全、执法、消防及相关保护服务学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Homeland Security, Law Enforcement, Firefighting And Related Protective Services.": "国土安全、执法、消防及相关保护服务学年至少一年但不足两年证书。",
    "Associate degree in Homeland Security, Law Enforcement, Firefighting And Related Protective Services.": "国土安全、执法、消防及相关保护服务副学士学位。",
    "Award of at least two but less than four academic years in Homeland Security, Law Enforcement, Firefighting And Related Protective Services.": "国土安全、执法、消防及相关保护服务学年至少两年但不足四年奖项。",
    "Bachelor's degree in Homeland Security, Law Enforcement, Firefighting And Related Protective Services.": "国土安全、执法、消防及相关保护服务学士学位。",
    "Certificate of less than one academic year in Public Administration And Social Service Professions.": "公共管理与社会服务职业学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Public Administration And Social Service Professions.": "公共管理与社会服务职业学年至少一年但不足两年证书。",
    "Associate degree in Public Administration And Social Service Professions.": "公共管理与社会服务职业副学士学位。",
    "Award of at least two but less than four academic years in Public Administration And Social Service Professions.": "公共管理与社会服务职业学年至少两年但不足四年奖项。",
    "Bachelor's degree in Public Administration And Social Service Professions.": "公共管理与社会服务职业学士学位。",
    "Certificate of less than one academic year in Social Sciences.": "社会科学学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Social Sciences.": "社会科学学年至少一年但不足两年证书。",
    "Associate degree in Social Sciences.": "社会科学副学士学位。",
    "Award of at least two but less than four academic years in Social Sciences.": "社会科学学年至少两年但不足四年奖项。",
    "Bachelor's degree in Social Sciences.": "社会科学学士学位。",
    "Certificate of less than one academic year in Construction Trades.": "建筑贸易学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Construction Trades.": "建筑贸易学年至少一年但不足两年证书。",
    "Associate degree in Construction Trades.": "建筑贸易副学士学位。",
    "Award of at least two but less than four academic years in Construction Trades.": "建筑贸易学年至少两年但不足四年奖项。",
    "Bachelor's degree in Construction Trades.": "建筑贸易学士学位。",
    "Certificate of less than one academic year in Mechanic And Repair Technologies/Technicians.": "机械与维修技术/技术人员学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Mechanic And Repair Technologies/Technicians.": "机械与维修技术/技术人员学年至少一年但不足两年证书。",
    "Associate degree in Mechanic And Repair Technologies/Technicians.": "机械与维修技术/技术人员副学士学位。",
    "Award of at least two but less than four academic years in Mechanic And Repair Technologies/Technicians.": "机械与维修技术/技术人员学年至少两年但不足四年奖项。",
    "Bachelor's degree in Mechanic And Repair Technologies/Technicians.": "机械与维修技术/技术人员学士学位。",
    "Certificate of less than one academic year in Precision Production.": "精密生产学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Precision Production.": "精密生产学年至少一年但不足两年证书。",
    "Associate degree in Precision Production.": "精密生产副学士学位。",
    "Award of at least two but less than four academic years in Precision Production.": "精密生产学年至少两年但不足四年奖项。",
    "Bachelor's degree in Precision Production.": "精密生产学士学位。",
    "Certificate of less than one academic year in Transportation And Materials Moving.": "运输与材料搬运学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Transportation And Materials Moving.": "运输与材料搬运学年至少一年但不足两年证书。",
    "Associate degree in Transportation And Materials Moving.": "运输与材料搬运副学士学位。",
    "Award of at least two but less than four academic years in Transportation And Materials Moving.": "运输与材料搬运学年至少两年但不足四年奖项。",
    "Bachelor's degree in Transportation And Materials Moving.": "运输与材料搬运学士学位。",
    "Certificate of less than one academic year in Visual And Performing Arts.": "视觉与表演艺术学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Visual And Performing Arts.": "视觉与表演艺术学年至少一年但不足两年证书。",
    "Associate degree in Visual And Performing Arts.": "视觉与表演艺术副学士学位。",
    "Award of at least two but less than four academic years in Visual And Performing Arts.": "视觉与表演艺术学年至少两年但不足四年奖项。",
    "Bachelor's degree in Visual And Performing Arts.": "视觉与表演艺术学士学位。",
    "Certificate of less than one academic year in Health Professions And Related Programs.": "健康职业及相关项目学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Health Professions And Related Programs.": "健康职业及相关项目学年至少一年但不足两年证书。",
    "Associate degree in Health Professions And Related Programs.": "健康职业及相关项目副学士学位。",
    "Award of at least two but less than four academic years in Health Professions And Related Programs.": "健康职业及相关项目学年至少两年但不足四年奖项。",
    "Bachelor's degree in Health Professions And Related Programs.": "健康职业及相关项目学士学位。",
    "Certificate of less than one academic year in Business, Management, Marketing, And Related Support Services.": "商业、管理、市场营销及相关支持服务学年不足一年证书。",
    "Certificate of at least one but less than two academic years in Business, Management, Marketing, And Related Support Services.": "商业、管理、市场营销及相关支持服务学年至少一年但不足两年证书。",
    "Associate degree in Business, Management, Marketing, And Related Support Services.": "商业、管理、市场营销及相关支持服务副学士学位。",
    "Award of at least two but less than four academic years in Business, Management, Marketing, And Related Support Services.": "商业、管理、市场营销及相关支持服务学年至少两年但不足四年奖项。",
    "Bachelor's degree in Business, Management, Marketing, And Related Support Services.": "商业、管理、市场营销及相关支持服务学士学位。",
    "Certificate of less than one academic year in History.": "历史学年不足一年证书。",
    "Certificate of at least one but less than two academic years in History.": "历史学年至少一年但不足两年证书。",
    "Associate degree in History.": "历史副学士学位。",
    "Award of at least two but less than four academic years in History.": "历史学年至少两年但不足四年奖项。",
    "Bachelor's degree in History.": "历史学士学位。",
    "Flag for distance-education-only education": "仅提供远程教育的标记",
    "Enrollment of undergraduate certificate/degree-seeking students": "本科证书/学位寻求学生入学情况",
    "Enrollment of all undergraduate students": "所有本科生入学情况",
    "Total share of enrollment of undergraduate degree-seeking students who are white": "本科证书/学位寻求学生中白人占比",
    "Total share of enrollment of undergraduate degree-seeking students who are black": "本科证书/学位寻求学生中黑人占比",
    "Total share of enrollment of undergraduate degree-seeking students who are Hispanic": "本科证书/学位寻求学生中西班牙裔占比",
    "Total share of enrollment of undergraduate degree-seeking students who are Asian": "本科证书/学位寻求学生中亚裔占比",
    "Total share of enrollment of undergraduate degree-seeking students who are American Indian/Alaska Native": "本科证书/学位寻求学生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of undergraduate degree-seeking students who are Native Hawaiian/Pacific Islander": "本科证书/学位寻求学生中夏威夷原住民/太平洋岛屿居民占比",
    "Total share of enrollment of undergraduate degree-seeking students who are two or more races": "本科证书/学位寻求学生中多种族占比",
    "Total share of enrollment of undergraduate degree-seeking students who are non-resident aliens": "本科证书/学位寻求学生中非居民外国人占比",
    "Total share of enrollment of undergraduate degree-seeking students whose race is unknown": "本科证书/学位寻求学生中种族未知占比",
    "Total share of enrollment of undergraduate degree-seeking students who are white non-Hispanic": "本科证书/学位寻求学生中非西班牙裔白人占比",
    "Total share of enrollment of undergraduate degree-seeking students who are black non-Hispanic": "本科证书/学位寻求学生中非西班牙裔黑人占比",
    "Total share of enrollment of undergraduate degree-seeking students who are Asian/Pacific Islander": "本科证书/学位寻求学生中亚裔/太平洋岛屿居民占比",
    "Total share of enrollment of undergraduate degree-seeking students who are American Indian/Alaska Native": "本科证书/学位寻求学生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of undergraduate degree-seeking students who are Hispanic": "本科证书/学位寻求学生中西班牙裔占比",
    "Total share of enrollment of undergraduate students who are non-resident aliens": "本科生中非居民外国人占比",
    "Total share of enrollment of undergraduate students whose race is unknown": "本科生中种族未知占比",
    "Total share of enrollment of undergraduate students who are white non-Hispanic": "本科生中非西班牙裔白人占比",
    "Total share of enrollment of undergraduate students who are black non-Hispanic": "本科生中非西班牙裔黑人占比",
    "Total share of enrollment of undergraduate students who are Asian/Pacific Islander": "本科生中亚裔/太平洋岛屿居民占比",
    "Total share of enrollment of undergraduate students who are American Indian/Alaska Native": "本科生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of undergraduate students who are Hispanic": "本科生中西班牙裔占比",
    "Share of undergraduate, degree-/certificate-seeking students who are part-time": "本科证书/学位寻求学生中兼职学生的比例",
    "Flag for currently operating institution, 0=closed, 1=operating": "当前运行机构标记，0=关闭，1=运行",
    "Average net price for Title IV institutions (public institutions)": "第IV章机构（公共机构）的平均净价格",
    "Average net price for Title IV institutions (private for-profit and nonprofit institutions)": "第IV章机构（私营营利和非营利机构）的平均净价格",
    "Average net price for the largest program at the institution for program-year institutions": "按学年机构的最大项目的平均净价格",
    "Average net price for the largest program at the institution for schools on 'other' academic year calendars": "按“其他”学年日历学校的最大项目的平均净价格",
    "Average net price for $0-$30,000 family income (public institutions)": "家庭收入0-$30,000（公共机构）的平均净价格",
    "Average net price for $30,001-$48,000 family income (public institutions)": "家庭收入$30,001-$48,000（公共机构）的平均净价格",
    "Average net price for $48,001-$75,000 family income (public institutions)": "家庭收入$48,001-$75,000（公共机构）的平均净价格",
    "Average net price for $75,001-$110,000 family income (public institutions)": "家庭收入$75,001-$110,000（公共机构）的平均净价格",
    "Average net price for $110,000+ family income (public institutions)": "家庭收入$110,000+（公共机构）的平均净价格",
    "Average net price for $0-$30,000 family income (private for-profit and nonprofit institutions)": "家庭收入0-$30,000（私营营利和非营利机构）的平均净价格",
    "Average net price for $30,001-$48,000 family income (private for-profit and nonprofit institutions)": "家庭收入$30,001-$48,000（私营营利和非营利机构）的平均净价格",
    "Average net price for $48,001-$75,000 family income (private for-profit and nonprofit institutions)": "家庭收入$48,001-$75,000（私营营利和非营利机构）的平均净价格",
    "Average net price for $75,001-$110,000 family income (private for-profit and nonprofit institutions)": "家庭收入$75,001-$110,000（私营营利和非营利机构）的平均净价格",
    "Average net price for $110,000+ family income (private for-profit and nonprofit institutions)": "家庭收入$110,000+（私营营利和非营利机构）的平均净价格",
    "Average net price for $0-$30,000 family income (program-year institutions)": "家庭收入0-$30,000（学年机构）的平均净价格",
    "Average net price for $30,001-$48,000 family income (program-year institutions)": "家庭收入$30,001-$48,000（学年机构）的平均净价格",
    "Average net price for $48,001-$75,000 family income (program-year institutions)": "家庭收入$48,001-$75,000（学年机构）的平均净价格",
    "Average net price for $75,001-$110,000 family income (program-year institutions)": "家庭收入$75,001-$110,000（学年机构）的平均净价格",
    "Average net price for $110,000+ family income (program-year institutions)": "家庭收入$110,000+（学年机构）的平均净价格",
    "Average net price for $0-$30,000 family income (other academic calendar institutions)": "家庭收入0-$30,000（其他学年日历机构）的平均净价格",
    "Average net price for $30,001-$48,000 family income (other academic calendar institutions)": "家庭收入$30,001-$48,000（其他学年日历机构）的平均净价格",
    "Average net price for $48,001-$75,000 family income (other academic calendar institutions)": "家庭收入$48,001-$75,000（其他学年日历机构）的平均净价格",
    "Average net price for $75,001-$110,000 family income (other academic calendar institutions)": "家庭收入$75,001-$110,000（其他学年日历机构）的平均净价格",
    "Average net price for $110,000+ family income (other academic calendar institutions)": "家庭收入$110,000+（其他学年日历机构）的平均净价格",
    "Average net price for $0-$48,000 family income (public institutions)": "家庭收入0-$48,000（公共机构）的平均净价格",
    "Average net price for $0-$48,000 family income (private for-profit and nonprofit institutions)": "家庭收入0-$48,000（私营营利和非营利机构）的平均净价格",
    "Average net price for $0-$48,000 family income (program-year institutions)": "家庭收入0-$48,000（学年机构）的平均净价格",
    "Average net price for $0-$48,000 family income (other academic calendar institutions)": "家庭收入0-$48,000（其他学年日历机构）的平均净价格",
    "Average net price for $48,001-$110,000 family income (public institutions)": "家庭收入$48,001-$110,000（公共机构）的平均净价格",
    "Average net price for $48,001-$110,000 family income (private for-profit and nonprofit institutions)": "家庭收入$48,001-$110,000（私营营利和非营利机构）的平均净价格",
    "Average net price for $48,001-$110,000 family income (program-year institutions)": "家庭收入$48,001-$110,000（学年机构）的平均净价格",
    "Average net price for $48,001-$110,000 family income (other academic calendar institutions)": "家庭收入$48,001-$110,000（其他学年日历机构）的平均净价格",
    "Average net price for $110,000+ family income (public institutions)": "家庭收入$110,000+（公共机构）的平均净价格",
    "Average net price for $110,000+ family income (private for-profit and nonprofit institutions)": "家庭收入$110,000+（私营营利和非营利机构）的平均净价格",
    "Average net price for $110,000+ family income (program-year institutions)": "家庭收入$110,000+（学年机构）的平均净价格",
    "Average net price for $110,000+ family income (other academic calendar institutions)": "家庭收入$110,000+（其他学年日历机构）的平均净价格",
    "Flag for availability of distance education": "远程教育的可用性标记",
    "Total share of enrollment of undergraduate degree-seeking students who are not US citizens or permanent residents": "本科证书/学位寻求学生中非美国公民或永久居民占比",
    "Total share of enrollment of undergraduate students who are not US citizens or permanent residents": "本科生中非美国公民或永久居民占比",
    "Total share of enrollment of graduate degree-seeking students who are not US citizens or permanent residents": "研究生证书/学位寻求学生中非美国公民或永久居民占比",
    "Total share of enrollment of graduate students who are not US citizens or permanent residents": "研究生中非美国公民或永久居民占比",
    "Flag for availability of full-time enrollment": "全日制入学可用性标记",
    "Total share of enrollment of graduate students who are white": "研究生中白人占比",
    "Total share of enrollment of graduate students who are black": "研究生中黑人占比",
    "Total share of enrollment of graduate students who are Hispanic": "研究生中西班牙裔占比",
    "Total share of enrollment of graduate students who are Asian": "研究生中亚裔占比",
    "Total share of enrollment of graduate students who are American Indian/Alaska Native": "研究生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of graduate students who are Native Hawaiian/Pacific Islander": "研究生中夏威夷原住民/太平洋岛屿居民占比",
    "Total share of enrollment of graduate students who are two or more races": "研究生中多种族占比",
    "Total share of enrollment of graduate students who are non-resident aliens": "研究生中非居民外国人占比",
    "Total share of enrollment of graduate students whose race is unknown": "研究生中种族未知占比",
    "Total share of enrollment of graduate students who are white non-Hispanic": "研究生中非西班牙裔白人占比",
    "Total share of enrollment of graduate students who are black non-Hispanic": "研究生中非西班牙裔黑人占比",
    "Total share of enrollment of graduate students who are Asian/Pacific Islander": "研究生中亚裔/太平洋岛屿居民占比",
    "Total share of enrollment of graduate students who are American Indian/Alaska Native": "研究生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of graduate students who are Hispanic": "研究生中西班牙裔占比",
    "Flag for availability of graduate degree programs": "研究生学位项目的可用性标记",
    "Flag for availability of undergraduate degree programs": "本科生学位项目的可用性标记",
    "Average net price for the largest program at the institution for undergraduate programs": "本科项目中最大项目的平均净价格",
    "Average net price for the largest program at the institution for graduate programs": "研究生项目中最大项目的平均净价格",
    "Average net price for the largest program at the institution for distance education programs": "远程教育项目中最大项目的平均净价格",
    "Flag for availability of undergraduate programs": "本科项目的可用性标记",
    "Flag for availability of graduate programs": "研究生项目的可用性标记",
    "Flag for availability of distance education programs": "远程教育项目的可用性标记",
    "Total share of enrollment of graduate degree-seeking students who are white": "研究生证书/学位寻求学生中白人占比",
    "Total share of enrollment of graduate degree-seeking students who are black": "研究生证书/学位寻求学生中黑人占比",
    "Total share of enrollment of graduate degree-seeking students who are Hispanic": "研究生证书/学位寻求学生中西班牙裔占比",
    "Total share of enrollment of graduate degree-seeking students who are Asian": "研究生证书/学位寻求学生中亚裔占比",
    "Total share of enrollment of graduate degree-seeking students who are American Indian/Alaska Native": "研究生证书/学位寻求学生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of graduate degree-seeking students who are Native Hawaiian/Pacific Islander": "研究生证书/学位寻求学生中夏威夷原住民/太平洋岛屿居民占比",
    "Total share of enrollment of graduate degree-seeking students who are two or more races": "研究生证书/学位寻求学生中多种族占比",
    "Total share of enrollment of graduate degree-seeking students who are non-resident aliens": "研究生证书/学位寻求学生中非居民外国人占比",
    "Total share of enrollment of graduate degree-seeking students whose race is unknown": "研究生证书/学位寻求学生中种族未知占比",
    "Total share of enrollment of graduate degree-seeking students who are white non-Hispanic": "研究生证书/学位寻求学生中非西班牙裔白人占比",
    "Total share of enrollment of graduate degree-seeking students who are black non-Hispanic": "研究生证书/学位寻求学生中非西班牙裔黑人占比",
    "Total share of enrollment of graduate degree-seeking students who are Asian/Pacific Islander": "研究生证书/学位寻求学生中亚裔/太平洋岛屿居民占比",
    "Total share of enrollment of graduate degree-seeking students who are American Indian/Alaska Native": "研究生证书/学位寻求学生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of graduate degree-seeking students who are Hispanic": "研究生证书/学位寻求学生中西班牙裔占比",
    "Flag for availability of graduate certificate programs": "研究生证书项目的可用性标记",
    "Flag for availability of undergraduate certificate programs": "本科证书项目的可用性标记",
    "Average net price for undergraduate certificate programs": "本科证书项目的平均净价格",
    "Average net price for graduate certificate programs": "研究生证书项目的平均净价格",
    "Total share of enrollment of undergraduate certificate-seeking students who are white": "本科证书寻求学生中白人占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are black": "本科证书寻求学生中黑人占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are Hispanic": "本科证书寻求学生中西班牙裔占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are Asian": "本科证书寻求学生中亚裔占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are American Indian/Alaska Native": "本科证书寻求学生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are Native Hawaiian/Pacific Islander": "本科证书寻求学生中夏威夷原住民/太平洋岛屿居民占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are two or more races": "本科证书寻求学生中多种族占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are non-resident aliens": "本科证书寻求学生中非居民外国人占比",
    "Total share of enrollment of undergraduate certificate-seeking students whose race is unknown": "本科证书寻求学生中种族未知占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are white non-Hispanic": "本科证书寻求学生中非西班牙裔白人占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are black non-Hispanic": "本科证书寻求学生中非西班牙裔黑人占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are Asian/Pacific Islander": "本科证书寻求学生中亚裔/太平洋岛屿居民占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are American Indian/Alaska Native": "本科证书寻求学生中美洲印第安人/阿拉斯加土著占比",
    "Total share of enrollment of undergraduate certificate-seeking students who are Hispanic": "本科证书寻求学生中西班牙裔占比",
    "Flag for availability of undergraduate certificate programs": "本科证书项目的可用性标记",
    "Flag for availability of graduate certificate programs": "研究生证书项目的可用性标记",
    "Average net price for $30,001-$75,000 family income (public institutions)": "收入在 $30,001-$75,000 的家庭在公立机构的平均净价格",
    "Average net price for $30,001-$75,000 family income (private for-profit and nonprofit institutions)": "收入在 $30,001-$75,000 的家庭在私立营利和非营利机构的平均净价格",
    "Average net price for $75,000+ family income (public institutions)": "收入在 $75,000 及以上的家庭在公立机构的平均净价格",
    "Average net price for $75,000+ family income (private for-profit and nonprofit institutions)": "收入在 $75,000 及以上的家庭在私立营利和非营利机构的平均净价格",
    "Average net price for $30,001-$75,000 family income (program-year institutions)": "收入在 $30,001-$75,000 的家庭在项目年制机构的平均净价格",
    "Average net price for $30,001-$75,000 family income (other academic calendar institutions)": "收入在 $30,001-$75,000 的家庭在其他学术日历机构的平均净价格",
    "Average net price for $75,000+ family income (program-year institutions)": "收入在 $75,000 及以上的家庭在项目年制机构的平均净价格",
    "Average net price for $75,000+ family income (other academic calendar institutions)": "收入在 $75,000 及以上的家庭在其他学术日历机构的平均净价格",
    "Number of Title IV students (public institutions)": "公立机构中 Title IV 学生的数量",
    "Number of Title IV students (private for-profit and nonprofit institutions)": "私立营利和非营利机构中 Title IV 学生的数量",
    "Number of Title IV students (program-year institutions)": "项目年制机构中 Title IV 学生的数量",
    "Number of Title IV students (other academic calendar institutions)": "其他学术日历机构中 Title IV 学生的数量",
    "Number of Title IV students, $0-$30,000 family income (public institutions)": "收入在 $0-$30,000 的家庭在公立机构中的 Title IV 学生数量",
    "Number of Title IV students, $30,001-$48,000 family income (public institutions)": "收入在 $30,001-$48,000 的家庭在公立机构中的 Title IV 学生数量",
    "Number of Title IV students, $48,001-$75,000 family income (public institutions)": "收入在 $48,001-$75,000 的家庭在公立机构中的 Title IV 学生数量",
    "Number of Title IV students, $75,001-$110,000 family income (public institutions)": "收入在 $75,001-$110,000 的家庭在公立机构中的 Title IV 学生数量",
    "Number of Title IV students, $110,000+ family income (public institutions)": "收入在 $110,000 及以上的家庭在公立机构中的 Title IV 学生数量",
    "Number of Title IV students, $0-$30,000 family income (private for-profit and nonprofit institutions)": "收入在 $0-$30,000 的家庭在私立营利和非营利机构中的 Title IV 学生数量",
    "Number of Title IV students, $30,001-$48,000 family income (private for-profit and nonprofit institutions)": "收入在 $30,001-$48,000 的家庭在私立营利和非营利机构中的 Title IV 学生数量",
    "Number of Title IV students, $48,001-$75,000 family income (private for-profit and nonprofit institutions)": "收入在 $48,001-$75,000 的家庭在私立营利和非营利机构中的 Title IV 学生数量",
    "Number of Title IV students, $75,001-$110,000 family income (private for-profit and nonprofit institutions)": "收入在 $75,001-$110,000 的家庭在私立营利和非营利机构中的 Title IV 学生数量",
    "Number of Title IV students, $110,000+ family income (private for-profit and nonprofit institutions)": "收入在 $110,000 及以上的家庭在私立营利和非营利机构中的 Title IV 学生数量",
    "Number of Title IV students, $0-$30,000 family income (program-year institutions)": "收入在 $0-$30,000 的家庭在项目年制机构中的 Title IV 学生数量",
    "Number of Title IV students, $30,001-$48,000 family income (program-year institutions)": "收入在 $30,001-$48,000 的家庭在项目年制机构中的 Title IV 学生数量",
    "Number of Title IV students, $48,001-$75,000 family income (program-year institutions)": "收入在 $48,001-$75,000 的家庭在项目年制机构中的 Title IV 学生数量",
    "Number of Title IV students, $75,001-$110,000 family income (program-year institutions)": "收入在 $75,001-$110,000 的家庭在项目年制机构中的 Title IV 学生数量",
    "Number of Title IV students, $110,000+ family income (program-year institutions)": "收入在 $110,000 及以上的家庭在项目年制机构中的 Title IV 学生数量",
    "Number of Title IV students, $0-$30,000 family income (other academic calendar institutions)": "收入在 $0-$30,000 的家庭在其他学术日历机构中的 Title IV 学生数量",
    "Number of Title IV students, $30,001-$48,000 family income (other academic calendar institutions)": "收入在 $30,001-$48,000 的家庭在其他学术日历机构中的 Title IV 学生数量",
    "Number of Title IV students, $48,001-$75,000 family income (other academic calendar institutions)": "收入在 $48,001-$75,000 的家庭在其他学术日历机构中的 Title IV 学生数量",
    "Number of Title IV students, $75,001-$110,000 family income (other academic calendar institutions)": "收入在 $75,001-$110,000 的家庭在其他学术日历机构中的 Title IV 学生数量",
    "Number of Title IV students, $110,000+ family income (other academic calendar institutions)": "收入在 $110,000 及以上的家庭在其他学术日历机构中的 Title IV 学生数量",
    "Average cost of attendance (academic year institutions)": "学年制机构的平均就读费用",
    "Average cost of attendance (program-year institutions)": "项目年制机构的平均就读费用",
    "In-state tuition and fees": "本州学费和费用",
    "Out-of-state tuition and fees": "州外学费和费用",
    "Tuition and fees for program-year institutions": "项目年制机构的学费和费用",
    "Net tuition revenue per full-time equivalent student": "每全日制学生的净学费收入",
    "Instructional expenditures per full-time equivalent student": "每全日制学生的教学支出",
    "Average faculty salary": "平均教师薪资",
    "Proportion of faculty that is full-time": "全职教师比例",
    "Percentage of undergraduates who receive a Pell Grant": "获得 Pell Grant 的本科生百分比",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion)": "四年制机构首次全日制学生的完成率（预期完成时间的150%）",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion)": "少于四年制机构首次全日制学生的完成率（预期完成时间的150%）",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion), pooled for two year rolling averages": "四年制机构首次全日制学生的完成率（预期完成时间的150%），两年滚动平均值汇总",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion), pooled for two year rolling averages": "少于四年制机构首次全日制学生的完成率（预期完成时间的150%），两年滚动平均值汇总",
    "Years used for rolling averages of completion rate C150_[4/L4]_POOLED and transfer rate TRANS_[4/L4]_POOLED": "完成率 C150_[4/L4]_POOLED 和转学率 TRANS_[4/L4]_POOLED 的滚动平均值使用的年份",
    "Share of entering undergraduate students who are first-time, full-time degree-/certificate-seeking undergraduate students": "入学本科生中首次全日制学位/证书寻求者的比例",
    "Adjusted cohort count for completion rate at four-year institutions (denominator of 150% completion rate)": "四年制机构完成率的调整后队列计数（150% 完成率的分母）",
    "Adjusted cohort count for completion rate at less-than-four-year institutions (denominator of 150% completion rate)": "少于四年制机构完成率的调整后队列计数（150% 完成率的分母）",
    "Adjusted cohort count for transfer rate at four-year institutions (denominator of 150% transfer rate)": "四年制机构转学率的调整后队列计数（150% 转学率的分母）",
    "Adjusted cohort count for transfer rate at less-than-four-year institutions (denominator of 150% transfer rate)": "少于四年制机构转学率的调整后队列计数（150% 转学率的分母）",
    "Percentage of first-time, full-time students at four-year institutions that transferred to a four-year institution within three years": "四年制机构首次全日制学生在三年内转学至四年制机构的百分比",
    "Percentage of first-time, full-time students at less-than-four-year institutions that transferred to a four-year institution within three years": "少于四年制机构首次全日制学生在三年内转学至四年制机构的百分比",
    "Enrollment count for first-time, full-time degree-/certificate-seeking students at four-year institutions": "四年制机构首次全日制学位/证书寻求者的入学人数",
    "Enrollment count for first-time, full-time degree-/certificate-seeking students at less-than-four-year institutions": "少于四年制机构首次全日制学位/证书寻求者的入学人数",
    "First-time, full-time degree-/certificate-seeking students at four-year institutions": "四年制机构的首次全日制学位/证书寻求者",
    "First-time, full-time degree-/certificate-seeking students at less-than-four-year institutions": "少于四年制机构的首次全日制学位/证书寻求者",
    "Adjusted cohort count for completion rate at four-year institutions (denominator of 150% completion rate), pooled for two-year rolling averages": "四年制机构的调整队列计数（150％完成率的分母），用于两年滚动平均",
    "Adjusted cohort count for completion rate at less-than-four-year institutions (denominator of 150% completion rate), pooled for two-year rolling averages": "少于四年制机构的调整队列计数（150％完成率的分母），用于两年滚动平均",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for white students": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 白人学生",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for black students": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 黑人学生",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for Hispanic students": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 西班牙裔学生",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for Asian students": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 亚洲学生",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for American Indian/Alaska Native students": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 美洲印第安人/阿拉斯加原住民学生",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for Native Hawaiian/Pacific Islander students": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 夏威夷原住民/太平洋岛民学生",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for students of two-or-more-races": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 混合种族学生",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for non-resident alien students": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 非居民外国学生",
    "Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion) for students whose race is unknown": "四年制机构首次全日制学生的完成率（150％预计完成时间） - 种族未知的学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for white students": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 白人学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for black students": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 黑人学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for Hispanic students": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 西班牙裔学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for Asian students": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 亚洲学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for American Indian/Alaska Native students": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 美洲印第安人/阿拉斯加原住民学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for Native Hawaiian/Pacific Islander students": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 夏威夷原住民/太平洋岛民学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for students of two-or-more-races": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 混合种族学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for non-resident alien students": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 非居民外国学生",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (150% of expected time to completion) for students whose race is unknown": "少于四年制机构首次全日制学生的完成率（150％预计完成时间） - 种族未知的学生",
    "Completion rate for first-time, full-time bachelor's-degree-seeking students at four-year institutions (200% of expected time to completion)": "四年制机构首次全日制学士学位学生的完成率（200％预计完成时间）",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (200% of expected time to completion)": "少于四年制机构首次全日制学生的完成率（200％预计完成时间）",
    "Adjusted cohort count for completion rate at four-year institutions (denominator of 200% completion rate)": "四年制机构的调整队列计数（200％完成率的分母）",
    "Adjusted cohort count for completion rate at less-than-four-year institutions (denominator of 200% completion rate)": "少于四年制机构的调整队列计数（200％完成率的分母）",
    "First-time, full-time student retention rate at four-year institutions": "四年制机构首次全日制学生的保留率",
    "First-time, full-time student retention rate at less-than-four-year institutions": "少于四年制机构首次全日制学生的保留率",
    "First-time, part-time student retention rate at four-year institutions": "四年制机构首次兼职学生的保留率",
    "First-time, part-time student retention rate at less-than-four-year institutions": "少于四年制机构首次兼职学生的保留率",
    "Completion rate for first-time, full-time bachelor's-degree-seeking students at four-year institutions (200% of expected time to completion), pooled for two year rolling averages": "四年制机构首次全日制学士学位学生的完成率（200％预计完成时间），用于两年滚动平均",
    "Completion rate for first-time, full-time students at less-than-four-year institutions (200% of expected time to completion), pooled for two year rolling averages": "少于四年制机构首次全日制学生的完成率（200％预计完成时间），用于两年滚动平均",
    "Years used for rolling averages of completion rate C200_[4/L4]_POOLED": "用于滚动平均的完成率年份C200_[4/L4]_POOLED",
    "Adjusted cohort count for completion rate at four-year institutions (denominator of 200% completion rate), pooled for two-year rolling averages": "四年制机构的调整队列计数（200％完成率的分母），用于两年滚动平均",
    "Adjusted cohort count for completion rate at less-than-four-year institutions (denominator of 200% completion rate), pooled for two-year rolling averages": "少于四年制机构的调整队列计数（200％完成率的分母），用于两年滚动平均",
    "Percent of all undergraduate students receiving a federal student loan": "获得联邦学生贷款的本科生百分比",
    "Percentage of undergraduates aged 25 and above": "年龄在25岁及以上的本科生百分比",
    "Two-year cohort default rate": "两年队列违约率",
    "Three-year cohort default rate": "三年队列违约率",
    "Percent died within 2 years at original institution": "在原始机构内2年内死亡的百分比",
    "Percent completed within 2 years at original institution": "在原始机构内2年内完成的百分比",
    "Percent who transferred to a 4-year institution and completed within 2 years": "转到四年制机构并在2年内完成的百分比",
    "Percent who transferred to a 2-year institution and completed within 2 years": "转到两年制机构并在2年内完成的百分比",
    "Percent withdrawn from original institution within 2 years": "在2年内从原始机构退出的百分比",
    "Percent who transferred to a 4-year institution and withdrew within 2 years": "转到四年制机构并在2年内退出的百分比",
    "Percent who transferred to a 2-year institution and withdrew within 2 years": "转到两年制机构并在2年内退出的百分比",
    "Percent still enrolled at original institution within 2 years": "在2年内仍然在原始机构注册的百分比",
    "Percent who transferred to a 4-year institution and were still enrolled within 2 years": "转到四年制机构并在2年内仍然注册的百分比",
    "Percent who transferred to a 2-year institution and were still enrolled within 2 years": "转到两年制机构并在2年内仍然注册的百分比",
    "Percent with status unknown within 2 years at original institution": "在2年内在原始机构身份未知的百分比",
    "Percent who transferred to a 4-year institution and whose status is unknown within 2 years": "转到四年制机构并在2年内身份未知的百分比",
    "Percent who transferred to a 2-year institution and whose status is unknown within 2 years": "转到两年制机构并在2年内身份未知的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who died within 2 years at original institution": "低收入（家庭名义收入少于$30,000）学生在原始机构内2年内死亡的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who completed within 2 years at original institution": "低收入（家庭名义收入少于$30,000）学生在原始机构内2年内完成的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 4-year institution and completed within 2 years": "低收入（家庭名义收入少于$30,000）学生转到四年制机构并在2年内完成的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 2-year institution and completed within 2 years": "低收入（家庭名义收入少于$30,000）学生转到两年制机构并在2年内完成的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students withdrawn from original institution within 2 years": "低收入（家庭名义收入少于$30,000）学生在2年内从原始机构退出的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 4-year institution and withdrew within 2 years": "低收入（家庭名义收入少于$30,000）学生转到四年制机构并在2年内退出的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 2-year institution and withdrew within 2 years": "低收入（家庭名义收入少于$30,000）学生转到两年制机构并在2年内退出的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who were still enrolled at original institution within 2 years": "低收入（家庭名义收入少于$30,000）学生在原始机构内2年内仍然注册的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 4-year institution and were still enrolled within 2 years": "低收入（家庭名义收入少于$30,000）学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 2-year institution and were still enrolled within 2 years": "低收入（家庭名义收入少于$30,000）学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students with status unknown within 2 years at original institution": "低收入（家庭名义收入少于$30,000）学生在原始机构内2年内身份未知的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 4-year institution and whose status is unknown within 2 years": "低收入（家庭名义收入少于$30,000）学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 2-year institution and whose status is unknown within 2 years": "低收入（家庭名义收入少于$30,000）学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who died within 2 years at original institution": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在原始机构内2年内死亡的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who completed within 2 years at original institution": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在原始机构内2年内完成的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 4-year institution and completed within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到四年制机构并在2年内完成的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 2-year institution and completed within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到两年制机构并在2年内完成的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students withdrawn from original institution within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在2年内从原始机构退出的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 4-year institution and withdrew within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到四年制机构并在2年内退出的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 2-year institution and withdrew within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到两年制机构并在2年内退出的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who were still enrolled at original institution within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在原始机构内2年内仍然注册的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 4-year institution and were still enrolled within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 2-year institution and were still enrolled within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students with status unknown within 2 years at original institution": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在原始机构内2年内身份未知的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 4-year institution and whose status is unknown within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 2-year institution and whose status is unknown within 2 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who died within 2 years at original institution": "高收入（家庭名义收入高于$75,000）学生在原始机构内2年内死亡的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who completed within 2 years at original institution": "高收入（家庭名义收入高于$75,000）学生在原始机构内2年内完成的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 4-year institution and completed within 2 years": "高收入（家庭名义收入高于$75,000）学生转到四年制机构并在2年内完成的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 2-year institution and completed within 2 years": "高收入（家庭名义收入高于$75,000）学生转到两年制机构并在2年内完成的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students withdrawn from original institution within 2 years": "高收入（家庭名义收入高于$75,000）学生在2年内从原始机构退出的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 4-year institution and withdrew within 2 years": "高收入（家庭名义收入高于$75,000）学生转到四年制机构并在2年内退出的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 2-year institution and withdrew within 2 years": "高收入（家庭名义收入高于$75,000）学生转到两年制机构并在2年内退出的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who were still enrolled at original institution within 2 years": "高收入（家庭名义收入高于$75,000）学生在原始机构内2年内仍然注册的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 4-year institution and were still enrolled within 2 years": "高收入（家庭名义收入高于$75,000）学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 2-year institution and were still enrolled within 2 years": "高收入（家庭名义收入高于$75,000）学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students with status unknown within 2 years at original institution": "高收入（家庭名义收入高于$75,000）学生在原始机构内2年内身份未知的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 4-year institution and whose status is unknown within 2 years": "高收入（家庭名义收入高于$75,000）学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 2-year institution and whose status is unknown within 2 years": "高收入（家庭名义收入高于$75,000）学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of dependent students who died within 2 years at original institution": "受抚养学生在原始机构内2年内死亡的百分比",
    "Percent of dependent students who completed within 2 years at original institution": "受抚养学生在原始机构内2年内完成的百分比",
    "Percent of dependent students who transferred to a 4-year institution and completed within 2 years": "受抚养学生转到四年制机构并在2年内完成的百分比",
    "Percent of dependent students who transferred to a 2-year institution and completed within 2 years": "受抚养学生转到两年制机构并在2年内完成的百分比",
    "Percent of dependent students withdrawn from original institution within 2 years": "受抚养学生在2年内从原始机构退出的百分比",
    "Percent of dependent students who transferred to a 4-year institution and withdrew within 2 years": "受抚养学生转到四年制机构并在2年内退出的百分比",
    "Percent of dependent students who transferred to a 2-year institution and withdrew within 2 years": "受抚养学生转到两年制机构并在2年内退出的百分比",
    "Percent of dependent students who were still enrolled at original institution within 2 years": "受抚养学生在原始机构内2年内仍然注册的百分比",
    "Percent of dependent students who transferred to a 4-year institution and were still enrolled within 2 years": "受抚养学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of dependent students who transferred to a 2-year institution and were still enrolled within 2 years": "受抚养学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of dependent students with status unknown within 2 years at original institution": "受抚养学生在原始机构内2年内身份未知的百分比",
    "Percent of dependent students who transferred to a 4-year institution and whose status is unknown within 2 years": "受抚养学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of dependent students who transferred to a 2-year institution and whose status is unknown within 2 years": "受抚养学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of independent students who died within 2 years at original institution": "独立学生在原始机构内2年内死亡的百分比",
    "Percent of independent students who completed within 2 years at original institution": "独立学生在原始机构内2年内完成的百分比",
    "Percent of independent students who transferred to a 4-year institution and completed within 2 years": "独立学生转到四年制机构并在2年内完成的百分比",
    "Percent of independent students who transferred to a 2-year institution and completed within 2 years": "独立学生转到两年制机构并在2年内完成的百分比",
    "Percent of independent students withdrawn from original institution within 2 years": "独立学生在2年内从原始机构退出的百分比",
    "Percent of independent students who transferred to a 4-year institution and withdrew within 2 years": "独立学生转到四年制机构并在2年内退出的百分比",
    "Percent of independent students who transferred to a 2-year institution and withdrew within 2 years": "独立学生转到两年制机构并在2年内退出的百分比",
    "Percent of independent students who were still enrolled at original institution within 2 years": "独立学生在原始机构内2年内仍然注册的百分比",
    "Percent of independent students who transferred to a 4-year institution and were still enrolled within 2 years": "独立学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of independent students who transferred to a 2-year institution and were still enrolled within 2 years": "独立学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of independent students with status unknown within 2 years at original institution": "独立学生在原始机构内2年内身份未知的百分比",
    "Percent of independent students who transferred to a 4-year institution and whose status is unknown within 2 years": "独立学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of independent students who transferred to a 2-year institution and whose status is unknown within 2 years": "独立学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of female students who died within 2 years at original institution": "女性学生在原始机构内2年内死亡的百分比",
    "Percent of female students who completed within 2 years at original institution": "女性学生在原始机构内2年内完成的百分比",
    "Percent of female students who transferred to a 4-year institution and completed within 2 years": "女性学生转到四年制机构并在2年内完成的百分比",
    "Percent of female students who transferred to a 2-year institution and completed within 2 years": "女性学生转到两年制机构并在2年内完成的百分比",
    "Percent of female students withdrawn from original institution within 2 years": "女性学生在2年内从原始机构退出的百分比",
    "Percent of female students who transferred to a 4-year institution and withdrew within 2 years": "女性学生转到四年制机构并在2年内退出的百分比",
    "Percent of female students who transferred to a 2-year institution and withdrew within 2 years": "女性学生转到两年制机构并在2年内退出的百分比",
    "Percent of female students who were still enrolled at original institution within 2 years": "女性学生在原始机构内2年内仍然注册的百分比",
    "Percent of female students who transferred to a 4-year institution and were still enrolled within 2 years": "女性学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of female students who transferred to a 2-year institution and were still enrolled within 2 years": "女性学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of female students with status unknown within 2 years at original institution": "女性学生在原始机构内2年内身份未知的百分比",
    "Percent of female students who transferred to a 4-year institution and whose status is unknown within 2 years": "女性学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of female students who transferred to a 2-year institution and whose status is unknown within 2 years": "女性学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of male students who died within 2 years at original institution": "男性学生在原始机构内2年内死亡的百分比",
    "Percent of male students who completed within 2 years at original institution": "男性学生在原始机构内2年内完成的百分比",
    "Percent of male students who transferred to a 4-year institution and completed within 2 years": "男性学生转到四年制机构并在2年内完成的百分比",
    "Percent of male students who transferred to a 2-year institution and completed within 2 years": "男性学生转到两年制机构并在2年内完成的百分比",
    "Percent of male students withdrawn from original institution within 2 years": "男性学生在2年内从原始机构退出的百分比",
    "Percent of male students who transferred to a 4-year institution and withdrew within 2 years": "男性学生转到四年制机构并在2年内退出的百分比",
    "Percent of male students who transferred to a 2-year institution and withdrew within 2 years": "男性学生转到两年制机构并在2年内退出的百分比",
    "Percent of male students who were still enrolled at original institution within 2 years": "男性学生在原始机构内2年内仍然注册的百分比",
    "Percent of male students who transferred to a 4-year institution and were still enrolled within 2 years": "男性学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of male students who transferred to a 2-year institution and were still enrolled within 2 years": "男性学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of male students with status unknown within 2 years at original institution": "男性学生在原始机构内2年内身份未知的百分比",
    "Percent of male students who transferred to a 4-year institution and whose status is unknown within 2 years": "男性学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of male students who transferred to a 2-year institution and whose status is unknown within 2 years": "男性学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of students who received a Pell Grant at the institution and who died within 2 years at original institution": "在机构获得佩尔助学金的学生在原始机构内2年内死亡的百分比",
    "Percent of students who received a Pell Grant at the institution and who completed in 2 years at original institution": "在机构获得佩尔助学金的学生在原始机构内2年内完成的百分比",
    "Percent of students who received a Pell Grant at the institution and who transferred to a 4-year institution and completed within 2 years": "在机构获得佩尔助学金的学生转到四年制机构并在2年内完成的百分比",
    "Percent of students who received a Pell Grant at the institution and who transferred to a 2-year institution and completed within 2 years": "在机构获得佩尔助学金的学生转到两年制机构并在2年内完成的百分比",
    "Percent of students who received a Pell Grant at the institution and withdrew from original institution within 2 years": "在机构获得佩尔助学金的学生在2年内从原始机构退出的百分比",
    "Percent of students who received a Pell Grant at the institution and who transferred to a 4-year institution and withdrew within 2 years": "在机构获得佩尔助学金的学生转到四年制机构并在2年内退出的百分比",
    "Percent of students who received a Pell Grant at the institution and who transferred to a 2-year institution and withdrew within 2 years": "在机构获得佩尔助学金的学生转到两年制机构并在2年内退出的百分比",
    "Percent of students who received a Pell Grant at the institution and who were still enrolled at original institution within 2 years": "在机构获得佩尔助学金的学生在原始机构内2年内仍然注册的百分比",
    "Percent of students who received a Pell Grant at the institution and who transferred to a 4-year institution and were still enrolled within 2 years": "在机构获得佩尔助学金的学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of students who received a Pell Grant at the institution and who transferred to a 2-year institution and were still enrolled within 2 years": "在机构获得佩尔助学金的学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of students who received a Pell Grant at the institution and with status unknown within 2 years at original institution": "在机构获得佩尔助学金的学生在原始机构内2年内身份未知的百分比",
    "Percent of students who received a Pell Grant at the institution and who transferred to a 4-year institution and whose status is unknown within 2 years": "在机构获得佩尔助学金的学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of students who received a Pell Grant at the institution and who transferred to a 2-year institution and whose status is unknown within 2 years": "在机构获得佩尔助学金的学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of students who never received a Pell Grant at the institution and who died within 2 years at original institution": "在机构从未获得佩尔助学金的学生在原始机构内2年内死亡的百分比",
    "Percent of students who never received a Pell Grant at the institution and who completed in 2 years at original institution": "在机构从未获得佩尔助学金的学生在原始机构内2年内完成的百分比",
    "Percent of students who never received a Pell Grant at the institution and who transferred to a 4-year institution and completed within 2 years": "在机构从未获得佩尔助学金的学生转到四年制机构并在2年内完成的百分比",
    "Percent of students who never received a Pell Grant at the institution and who transferred to a 2-year institution and completed within 2 years": "在机构从未获得佩尔助学金的学生转到两年制机构并在2年内完成的百分比",
    "Percent of students who never received a Pell Grant at the institution and withdrew from original institution within 2 years": "在机构从未获得佩尔助学金的学生在2年内从原始机构退出的百分比",
    "Percent of students who never received a Pell Grant at the institution and who transferred to a 4-year institution and withdrew within 2 years": "在机构从未获得佩尔助学金的学生转到四年制机构并在2年内退出的百分比",
    "Percent of students who never received a Pell Grant at the institution and who transferred to a 2-year institution and withdrew within 2 years": "在机构从未获得佩尔助学金的学生转到两年制机构并在2年内退出的百分比",
    "Percent of students who never received a Pell Grant at the institution and who were still enrolled at original institution within 2 years": "在机构从未获得佩尔助学金的学生在原始机构内2年内仍然注册的百分比",
    "Percent of students who never received a Pell Grant at the institution and who transferred to a 4-year institution and were still enrolled within 2 years": "在机构从未获得佩尔助学金的学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of students who never received a Pell Grant at the institution and who transferred to a 2-year institution and were still enrolled within 2 years": "在机构从未获得佩尔助学金的学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of students who never received a Pell Grant at the institution and with status unknown within 2 years at original institution": "在机构从未获得佩尔助学金的学生在原始机构内2年内身份未知的百分比",
    "Percent of students who never received a Pell Grant at the institution and who transferred to a 4-year institution and whose status is unknown within 2 years": "在机构从未获得佩尔助学金的学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of students who never received a Pell Grant at the institution and who transferred to a 2-year institution and whose status is unknown within 2 years": "在机构从未获得佩尔助学金的学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of students who received a federal loan at the institution and who died within 2 years at original institution": "在机构获得联邦贷款的学生在原始机构内2年内死亡的百分比",
    "Percent of students who received a federal loan at the institution and who completed in 2 years at original institution": "在机构获得联邦贷款的学生在原始机构内2年内完成的百分比",
    "Percent of students who received a federal loan at the institution and who transferred to a 4-year institution and completed within 2 years": "在机构获得联邦贷款的学生转到四年制机构并在2年内完成的百分比",
    "Percent of students who received a federal loan at the institution and who transferred to a 2-year institution and completed within 2 years": "在机构获得联邦贷款的学生转到两年制机构并在2年内完成的百分比",
    "Percent of students who received a federal loan at the institution and withdrew from original institution within 2 years": "在机构获得联邦贷款的学生在2年内从原始机构退出的百分比",
    "Percent of students who received a federal loan at the institution and who transferred to a 4-year institution and withdrew within 2 years": "在机构获得联邦贷款的学生转到四年制机构并在2年内退出的百分比",
    "Percent of students who received a federal loan at the institution and who transferred to a 2-year institution and withdrew within 2 years": "在机构获得联邦贷款的学生转到两年制机构并在2年内退出的百分比",
    "Percent of students who received a federal loan at the institution and who were still enrolled at original institution within 2 years": "在机构获得联邦贷款的学生在原始机构内2年内仍然注册的百分比",
    "Percent of students who received a federal loan at the institution and who transferred to a 4-year institution and were still enrolled within 2 years": "在机构获得联邦贷款的学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of students who received a federal loan at the institution and who transferred to a 2-year institution and were still enrolled within 2 years": "在机构获得联邦贷款的学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of students who received a federal loan at the institution and with status unknown within 2 years at original institution": "在机构获得联邦贷款的学生在原始机构内2年内身份未知的百分比",
    "Percent of students who received a federal loan at the institution and who transferred to a 4-year institution and whose status is unknown within 2 years": "在机构获得联邦贷款的学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of students who received a federal loan at the institution and who transferred to a 2-year institution and whose status is unknown within 2 years": "在机构获得联邦贷款的学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of students who never received a federal loan at the institution and who died within 2 years at original institution": "在机构从未获得联邦贷款的学生在原始机构内2年内死亡的百分比",
    "Percent of students who never received a federal loan at the institution and who completed in 2 years at original institution": "在机构从未获得联邦贷款的学生在原始机构内2年内完成的百分比",
    "Percent of students who never received a federal loan at the institution and who transferred to a 4-year institution and completed within 2 years": "在机构从未获得联邦贷款的学生转到四年制机构并在2年内完成的百分比",
    "Percent of students who never received a federal loan at the institution and who transferred to a 2-year institution and completed within 2 years": "在机构从未获得联邦贷款的学生转到两年制机构并在2年内完成的百分比",
    "Percent of students who never received a federal loan at the institution and withdrew from original institution within 2 years": "在机构从未获得联邦贷款的学生在2年内从原始机构退出的百分比",
    "Percent of students who never received a federal loan at the institution and who transferred to a 4-year institution and withdrew within 2 years": "在机构从未获得联邦贷款的学生转到四年制机构并在2年内退出的百分比",
    "Percent of students who never received a federal loan at the institution and who transferred to a 2-year institution and withdrew within 2 years": "在机构从未获得联邦贷款的学生转到两年制机构并在2年内退出的百分比",
    "Percent of students who never received a federal loan at the institution and who were still enrolled at original institution within 2 years": "在机构从未获得联邦贷款的学生在原始机构内2年内仍然注册的百分比",
    "Percent of students who never received a federal loan at the institution and who transferred to a 4-year institution and were still enrolled within 2 years": "在机构从未获得联邦贷款的学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of students who never received a federal loan at the institution and who transferred to a 2-year institution and were still enrolled within 2 years": "在机构从未获得联邦贷款的学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of students who never received a federal loan at the institution and with status unknown within 2 years at original institution": "在机构从未获得联邦贷款的学生在原始机构内2年内身份未知的百分比",
    "Percent of students who never received a federal loan at the institution and who transferred to a 4-year institution and whose status is unknown within 2 years": "在机构从未获得联邦贷款的学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of students who never received a federal loan at the institution and who transferred to a 2-year institution and whose status is unknown within 2 years": "在机构从未获得联邦贷款的学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of first-generation students who died within 2 years at original institution": "第一代学生在原始机构内2年内死亡的百分比",
    "Percent of first-generation students who completed within 2 years at original institution": "第一代学生在原始机构内2年内完成的百分比",
    "Percent of first-generation students who transferred to a 4-year institution and completed within 2 years": "第一代学生转到四年制机构并在2年内完成的百分比",
    "Percent of first-generation students who transferred to a 2-year institution and completed within 2 years": "第一代学生转到两年制机构并在2年内完成的百分比",
    "Percent of first-generation students withdrawn from original institution within 2 years": "第一代学生在2年内从原始机构退出的百分比",
    "Percent of first-generation students who transferred to a 4-year institution and withdrew within 2 years": "第一代学生转到四年制机构并在2年内退出的百分比",
    "Percent of first-generation students who transferred to a 2-year institution and withdrew within 2 years": "第一代学生转到两年制机构并在2年内退出的百分比",
    "Percent of first-generation students who were still enrolled at original institution within 2 years": "第一代学生在原始机构内2年内仍然注册的百分比",
    "Percent of first-generation students who transferred to a 4-year institution and were still enrolled within 2 years": "第一代学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of first-generation students who transferred to a 2-year institution and were still enrolled within 2 years": "第一代学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of first-generation students with status unknown within 2 years at original institution": "第一代学生在原始机构内2年内身份未知的百分比",
    "Percent of first-generation students who transferred to a 4-year institution and whose status is unknown within 2 years": "第一代学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of first-generation students who transferred to a 2-year institution and whose status is unknown within 2 years": "第一代学生转到两年制机构并在2年内身份未知的百分比",
    "Percent of not-first-generation students who died within 2 years at original institution": "非第一代学生在原始机构内2年内死亡的百分比",
    "Percent of not-first-generation students who completed within 2 years at original institution": "非第一代学生在原始机构内2年内完成的百分比",
    "Percent of not-first-generation students who transferred to a 4-year institution and completed within 2 years": "非第一代学生转到四年制机构并在2年内完成的百分比",
    "Percent of not-first-generation students who transferred to a 2-year institution and completed within 2 years": "非第一代学生转到两年制机构并在2年内完成的百分比",
    "Percent of not-first-generation students withdrawn from original institution within 2 years": "非第一代学生在2年内从原始机构退出的百分比",
    "Percent of not-first-generation students who transferred to a 4-year institution and withdrew within 2 years": "非第一代学生转到四年制机构并在2年内退出的百分比",
    "Percent of not-first-generation students who transferred to a 2-year institution and withdrew within 2 years": "非第一代学生转到两年制机构并在2年内退出的百分比",
    "Percent of not-first-generation students who were still enrolled at original institution within 2 years": "非第一代学生在原始机构内2年内仍然注册的百分比",
    "Percent of not-first-generation students who transferred to a 4-year institution and were still enrolled within 2 years": "非第一代学生转到四年制机构并在2年内仍然注册的百分比",
    "Percent of not-first-generation students who transferred to a 2-year institution and were still enrolled within 2 years": "非第一代学生转到两年制机构并在2年内仍然注册的百分比",
    "Percent of not-first-generation students with status unknown within 2 years at original institution": "非第一代学生在原始机构内2年内身份未知的百分比",
    "Percent of not-first-generation students who transferred to a 4-year institution and whose status is unknown within 2 years": "非第一代学生转到四年制机构并在2年内身份未知的百分比",
    "Percent of not-first-generation students who transferred to a 2-year institution and whose status is unknown within 2 years": "非第一代学生转到两年制机构并在2年内身份未知的百分比",
    "Percent died within 3 years at original institution": "在原始机构内3年内死亡的百分比",
    "Percent completed within 3 years at original institution": "在原始机构内3年内完成的百分比",
    "Percent who transferred to a 4-year institution and completed within 3 years": "转到四年制机构并在3年内完成的百分比",
    "Percent who transferred to a 2-year institution and completed within 3 years": "转到两年制机构并在3年内完成的百分比",
    "Percent withdrawn from original institution within 3 years": "在3年内从原始机构退出的百分比",
    "Percent who transferred to a 4-year institution and withdrew within 3 years": "转到四年制机构并在3年内退出的百分比",
    "Percent who transferred to a 2-year institution and withdrew within 3 years": "转到两年制机构并在3年内退出的百分比",
    "Percent still enrolled at original institution within 3 years": "在3年内仍然在原始机构注册的百分比",
    "Percent who transferred to a 4-year institution and were still enrolled within 3 years": "转到四年制机构并在3年内仍然注册的百分比",
    "Percent who transferred to a 2-year institution and were still enrolled within 3 years": "转到两年制机构并在3年内仍然注册的百分比",
    "Percent with status unknown within 3 years at original institution": "在3年内在原始机构身份未知的百分比",
    "Percent who transferred to a 4-year institution and whose status is unknown within 3 years": "转到四年制机构并在3年内身份未知的百分比",
    "Percent who transferred to a 2-year institution and whose status is unknown within 3 years": "转到两年制机构并在3年内身份未知的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who died within 3 years at original institution": "低收入（家庭名义收入少于$30,000）学生在原始机构内3年内死亡的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who completed within 3 years at original institution": "低收入（家庭名义收入少于$30,000）学生在原始机构内3年内完成的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 4-year institution and completed within 3 years": "低收入（家庭名义收入少于$30,000）学生转到四年制机构并在3年内完成的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 2-year institution and completed within 3 years": "低收入（家庭名义收入少于$30,000）学生转到两年制机构并在3年内完成的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students withdrawn from original institution within 3 years": "低收入（家庭名义收入少于$30,000）学生在3年内从原始机构退出的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 4-year institution and withdrew within 3 years": "低收入（家庭名义收入少于$30,000）学生转到四年制机构并在3年内退出的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 2-year institution and withdrew within 3 years": "低收入（家庭名义收入少于$30,000）学生转到两年制机构并在3年内退出的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who were still enrolled at original institution within 3 years": "低收入（家庭名义收入少于$30,000）学生在原始机构内3年内仍然注册的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 4-year institution and were still enrolled within 3 years": "低收入（家庭名义收入少于$30,000）学生转到四年制机构并在3年内仍然注册的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 2-year institution and were still enrolled within 3 years": "低收入（家庭名义收入少于$30,000）学生转到两年制机构并在3年内仍然注册的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students with status unknown within 3 years at original institution": "低收入（家庭名义收入少于$30,000）学生在原始机构内3年内身份未知的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 4-year institution and whose status is unknown within 3 years": "低收入（家庭名义收入少于$30,000）学生转到四年制机构并在3年内身份未知的百分比",
    "Percent of low-income (less than $30,000 in nominal family income) students who transferred to a 2-year institution and whose status is unknown within 3 years": "低收入（家庭名义收入少于$30,000）学生转到两年制机构并在3年内身份未知的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who died within 3 years at original institution": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在原始机构内3年内死亡的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who completed within 3 years at original institution": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在原始机构内3年内完成的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 4-year institution and completed within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到四年制机构并在3年内完成的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 2-year institution and completed within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到两年制机构并在3年内完成的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students withdrawn from original institution within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在3年内从原始机构退出的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 4-year institution and withdrew within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到四年制机构并在3年内退出的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 2-year institution and withdrew within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到两年制机构并在3年内退出的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who were still enrolled at original institution within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在原始机构内3年内仍然注册的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 4-year institution and were still enrolled within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到四年制机构并在3年内仍然注册的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 2-year institution and were still enrolled within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到两年制机构并在3年内仍然注册的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students with status unknown within 3 years at original institution": "中等收入（家庭名义收入在$30,000到$75,000之间）学生在原始机构内3年内身份未知的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 4-year institution and whose status is unknown within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到四年制机构并在3年内身份未知的百分比",
    "Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who transferred to a 2-year institution and whose status is unknown within 3 years": "中等收入（家庭名义收入在$30,000到$75,000之间）学生转到两年制机构并在3年内身份未知的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who died within 3 years at original institution": "高收入（家庭名义收入高于$75,000）学生在原始机构内3年内死亡的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who completed within 3 years at original institution": "高收入（家庭名义收入高于$75,000）学生在原始机构内3年内完成的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 4-year institution and completed within 3 years": "高收入（家庭名义收入高于$75,000）学生转到四年制机构并在3年内完成的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 2-year institution and completed within 3 years": "高收入（家庭名义收入高于$75,000）学生转到两年制机构并在3年内完成的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students withdrawn from original institution within 3 years": "高收入（家庭名义收入高于$75,000）学生在3年内从原始机构退出的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 4-year institution and withdrew within 3 years": "高收入（家庭名义收入高于$75,000）学生转到四年制机构并在3年内退出的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 2-year institution and withdrew within 3 years": "高收入（家庭名义收入高于$75,000）学生转到两年制机构并在3年内退出的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who were still enrolled at original institution within 3 years": "高收入（家庭名义收入高于$75,000）学生在原始机构内3年内仍然注册的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 4-year institution and were still enrolled within 3 years": "高收入（家庭名义收入高于$75,000）学生转到四年制机构并在3年内仍然注册的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 2-year institution and were still enrolled within 3 years": "高收入（家庭名义收入高于$75,000）学生转到两年制机构并在3年内仍然注册的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students with status unknown within 3 years at original institution": "高收入（家庭名义收入高于$75,000）学生在原始机构内3年内身份未知的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 4-year institution and whose status is unknown within 3 years": "高收入（家庭名义收入高于$75,000）学生转到四年制机构并在3年内身份未知的百分比",
    "Percent of high-income (above $75,000 in nominal family income) students who transferred to a 2-year institution and whose status is unknown within 3 years": "高收入（家庭名义收入高于$75,000）学生转到两年制机构并在3年内身份未知的百分比",
    "Percent of dependent students who died within 3 years at original institution": "受抚养学生在原始机构内3年内死亡的百分比",
    "Percent of dependent students who completed within 3 years at original institution": "受抚养学生在原始机构内3年内完成的百分比",
    "Percent of dependent students who transferred to a 4-year institution and completed within 3 years": "受抚养学生转到四年制机构并在3年内完成的百分比",
    "Percent of dependent students who transferred to a 2-year institution and completed within 3 years": "受抚养学生转到两年制机构并在3年内完成的百分比",
    "Percent of dependent students withdrawn from original institution within 3 years": "受抚养学生在3年内从原始机构退出的百分比",
    "Percent of dependent students who transferred to a 4-year institution and withdrew within 3 years": "受抚养学生转到四年制机构并在3年内退出的百分比",
    "Percent of dependent students who transferred to a 2-year institution and withdrew within 3 years": "受抚养学生转到两年制机构并在3年内退出的百分比",
    "Percent of dependent students who were still enrolled at original institution within 3 years": "受抚养学生在原始机构内3年内仍然注册的百分比",
    "Percent of dependent students who transferred to a 4-year institution and were still enrolled within 3 years": "受抚养学生转到四年制机构并在3年内仍然注册的百分比",
    "Percent of dependent students who transferred to a 2-year institution and were still enrolled within 3 years": "受抚养学生转到两年制机构并在3年内仍然注册的百分比",
    "Percent of dependent students with status unknown within 3 years at original institution": "受抚养学生在原始机构内3年内身份未知的百分比",
    "Percent of dependent students who transferred to a 4-year institution and whose status is unknown within 3 years": "受抚养学生转到四年制机构并在3年内身份未知的百分比",
    "Percent of dependent students who transferred to a 2-year institution and whose status is unknown within 3 years": "受抚养学生转到两年制机构并在3年内身份未知的百分比",
    "Percent of independent students who died within 3 years at original institution": "独立学生在原始机构内3年内死亡的百分比",
    "Percent of independent students who completed within 3 years at original institution": "独立学生在原始机构内3年内完成的百分比",
    "Percent of independent students who transferred to a 4-year institution and completed within 3 years": "独立学生转到四年制机构并在3年内完成的百分比",
    "Percent of independent students who transferred to a 2-year institution and completed within 3 years": "独立学生转到两年制机构并在3年内完成的百分比",
    "Percent of independent students withdrawn from original institution within 3 years": "独立学生在3年内从原始机构退出的百分比",
    "Percent of independent students who transferred to a 4-year institution and withdrew within 3 years": "独立学生转到四年制机构并在3年内退出的百分比",
    "Percent of independent students who transferred to a 2-year institution and withdrew within 3 years": "独立学生转到两年制机构并在3年内退出的百分比",
    "Percent of independent students who were still enrolled at original institution within 3 years": "独立学生在原始机构内3年内仍然注册的百分比",
    "Percent of independent students who transferred to a 4-year institution and were still enrolled within 3 years": "独立学生转到四年制机构并在3年内仍然注册的百分比",
    "Percent of independent students who transferred to a 2-year institution and were still enrolled within 3 years": "独立学生转到两年制机构并在3年内仍然注册的百分比",
    "Percent of independent students with status unknown within 3 years at original institution": "独立学生在原始机构内3年内身份未知的百分比",
    "Percent of independent students who transferred to a 4-year institution and whose status is unknown within 3 years": "独立学生转到四年制机构并在3年内身份未知的百分比",
    "Percent of independent students who transferred to a 2-year institution and whose status is unknown within 3 years": "独立学生转到两年制机构并在3年内身份未知的百分比"
}

# Read the Excel file
file_path = '/学校排名数据/数据/大学录取率/Most-Recent-Cohorts-Institution_06102024/CollegeScorecardDataDictionary.xlsx'
df = pd.read_excel(file_path, sheet_name='Institution_Data_Dictionary')
# Replace the column names with their translations
df["NAME OF DATA ELEMENT"] = df["NAME OF DATA ELEMENT"].replace(translation_dict)


# Save the modified DataFrame back to an Excel file
df.to_excel('/学校排名数据/数据/大学录取率/Most-Recent-Cohorts-Institution_06102024/CollegeScorecard数据信息表.xlsx', index=False, sheet_name='Institution_Data_Dictionary')
